version: "3.9"

services:
  base:
    profiles: ["build"]
    image: ${IMG_REPO}/${IMG_NAME}:${IMG_TAG}
    build:
      context: ../..
      dockerfile: ./docker/base/Dockerfile

  test-gateway:
    profiles: ["test-gateway"]
    container_name: test-gateway
    image: ${IMG_REPO}/${IMG_NAME}:${IMG_TAG}
    init: true
    expose:
      - 9000
      - 9900
    command: ./scripts/test-gateway-ci.sh
