name: Test Trellis Build

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache Go modules
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-

    - name: Build Docker Image
      run: docker build -t trellis-test .

    - name: Run Tests
      run: docker run trellis-test go test ./...

    - name: Docker Compose Test
      run: |
        docker-compose -f docker/base/docker-compose.yml up --build --abort-on-container-exit
