version: "3.9"

services:
  base:
    profiles: ["build"]
    image: ${IMG_REPO}/${IMG_NAME}:${IMG_TAG}
    init: true
    build:
      context: ./

  xtrellis-test-gateway:
    profiles: ["test-gateway"]
    extends:
      service: base
    container_name: xtrellis-test-gateway
    expose:
      - 9000
      - 9900
    working_dir: /opt/trellis/cmd/xtrellis
    command: /bin/bash -cx "
      ./bin/run-coordinator-gateway.sh &
      sleep 10s ;
      ./bin/test-gateway-io.sh 102400
      "
