version: "3.9"

services:
  base:
    profiles: ["build"]
    image: ${IMG_REPO}/${IMG_NAME}:${IMG_TAG}
    init: true
    build:
      context: ./

  xtrellis-test-gateway:
    profiles: ["test-gateway"]
    extends:
      service: base
    container_name: xtrellis-test-gateway
    expose:
      - 9000
      - 9900
    command: ./scripts/test-gateway-ci.sh
